inherit_from:
  - https://dev.k.io/rubocop/rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "dennis-client.gemspec"

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
