name: CI
on: push
jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: krystal/release-please-manifest-action@v1
        id: release-please
        with:
          app-id: ${{ vars.RELEASE_PLEASE_GITHUB_APP_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_GITHUB_APP_PRIVATE_KEY }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Configure Bundler
        run: bundle config set rubygems.pkg.github.com "${{ secrets.KRYSTAL_GITHUB_PACKAGE_READ_KEY }}"

      - name: Install dependencies
        run: bundle install

      - name: Run linter
        run: bundle exec rake lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 3.0
          - 3.3
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}

      - name: Configure Bundler
        run: bundle config set rubygems.pkg.github.com "${{ secrets.KRYSTAL_GITHUB_PACKAGE_READ_KEY }}"

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test

  release:
    runs-on: ubuntu-latest
    needs: [release-please, lint, test]
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Build Gem
        run: gem build *.gemspec

      - name: Setup credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          printf -- ":github: Bearer ${GITHUB_API_KEY}\n" >> $HOME/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{secrets.KRYSTAL_RUBYGEMS_API_KEY}}
          GITHUB_API_KEY: ${{secrets.GITHUB_TOKEN}}

      - name: Publish to RubyGems
        run: |
          gem push *.gem

      - name: Publish to GPR
        run: |
          gem push --key github --host https://rubygems.pkg.github.com/krystal *.gem
